apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: spring-app

  template:
    metadata:
      labels:
        app: spring-app

    spec:
      containers:
      - name: spring-app
        image: jayadevarun2003/spring-k8s-demo
        ports:
        - containerPort: 8080

        env:
        - name: APP_NAME
          value: "Spring Kubernetes Demo"

        - name: ENVIRONMENT
          value: "Kubernetes"

        - name: APP_MESSAGE
          value: "Hello from Kubernetes"

        - name: DB_PASSWORD
          value: "password"
