spring.application.name=springproduct

spring.datasource.url=jdbc:mysql://localhost:3306/springproductdb
spring.datasource.username=product
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080