server {
    listen 80;
    server_name _;

    resolver 10.96.0.10 valid=10s;

    set $auth_upstream "http://auth-svc.healthcare.svc.cluster.local:3001";
    set $doctorupstream "http://doctor-svc.healthcare.svc.cluster.local:3002";
    set $patient_upstream "http://patient-svc.healthcare.svc.cluster.local:3003";
    set $appointment_upstream "http://appointment-svc.healthcare.svc.cluster.local:3004";
    set $pharmacy_upstream "http://pharmacy-svc.healthcare.svc.cluster.local:3005";
    set $lab_upstream "http://lab-svc.healthcare.svc.cluster.local:3006";

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth {
        proxy_pass $auth_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location /api/doctors/{
        proxy_pass $doctor_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location /api/patients {
        proxy_pass $patient_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location /api/appointments {
        proxy_pass $appointment_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location /api/pharmacy {
        proxy_pass $pharmacy_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location /api/labs {
        proxy_pass $lab_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }

    location /health {
        access_log off;
        return 200 '{"status":"healthy","service":"frontend"}';
        add_header Content-Type application/json;
    }
}
