apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod-demo
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: pvc-vol
      mountPath: /data
  volumes:
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: my-pvc
